# move this docker-compose.yml up a folder and create bot_token.txt with bot token

services:
  bot:
    build:
      context: ./Orari-Treni-Live-Bot
    command: "python main.py"
    volumes:
      - ./data:/home/bot/volume
    environment:
      DOCKER_MODE: 1
      LOG_LEVEL: INFO
    secrets:
      - bot_token

secrets:
  bot_token:
    file: bot_token.txt